### ISSUE TITLE
Update NuGet package for MSVS 2015

### ISSUE THREAD

**Issue by igagis** [coapp-packages/cairo#1]
Please, update the NuGet package to support v140 tools

**Comment by madewokherd** [comment]
The NuGet package has nothing to do with this repo. This is from an earlier version of CoApp, and we never updated it to produce NuGet packages.

You'll have to contact the package author through nuget.org.

**Comment by igagis** [comment]
I contacted the author but he did not reply. Is there a possibility to upload cairo to nuget as a CoApp thing from this repo?

**Comment by madewokherd** [comment]
It's not trivial, as someone would have to update the build scripts to produce all the needed variations, and add a .autopkg script. Also, we'd have to choose a new name for the package on nuget.

At the moment, I have my hands full just updating the existing packages.

**Comment by igagis** [comment]
I made packaging for static lib and uploaded to nuget.org as cairo_static

Here is the PR for reference: https://github.com/coapp-packages/cairo/pull/2

**Comment by igagis** [comment]
not needed anymore
